#!/bin/bash

venv=$(dirname $0)
port=$1
[[ $port == "" ]] && port=8000
# Unless --nostatic is specified, static files will be served as well
$venv/bin/python $venv/src/manage.py runserver 0.0.0.0:$port --settings system.settings.development
